SECRET_KEY = 'x8_g%t@huk!-e85dw@*e0j@6ce=c1cvm@eft_390jk*_2yb4*v'

AWS_STORAGE_BUCKET_NAME = 's3-draftto-usw1'
AWS_S3_REGION_NAME = 'us-west-1'  # e.g. us-east-2
AWS_ACCESS_KEY_ID = 'AKIAISLQ2BYSHHNT3DOA'
AWS_SECRET_ACCESS_KEY = 'HlwyjMNa8O87APV9pvD39cKEJ+ztPIsFKfMlTHWC'